name: Deploy Azure Function App (Python v2)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"   # match your Azure Function runtime

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: fetch-fabric-sql     # must match your Function App name in Azure
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: .
